In [1]:
import pandas as pd
import nltk
nltk.download('wordnet')

from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer 
porter = PorterStemmer()
lemmatizer = WordNetLemmatizer()


File = pd.read_csv('Dataset/Emotion_Lexicon.csv', encoding='latin-1')
File = File.drop(["Charged"], axis=1)
File.head(10)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Alee\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,Words,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust
0,march,0,0,0,0,0,0,1,0,0,0
1,august,0,0,0,0,0,0,1,0,0,0
2,ago,0,0,0,0,0,0,0,0,0,0
3,mar,0,0,0,0,0,1,0,0,0,0
4,vie,0,0,0,0,0,0,0,0,0,0
5,sun,0,1,0,0,1,0,1,0,1,1
6,wed,0,0,0,0,0,0,0,0,0,0
7,aback,0,0,0,0,0,0,0,0,0,0
8,abacus,0,0,0,0,0,0,0,0,0,1
9,abandon,0,0,0,1,0,1,0,1,0,0

In [2]:
    anger = []
    anticipation=[]
    disgust=[]
    fear=[]
    joy=[]
    negative=[]
    positive=[]
    sadness=[]
    surprise=[]
    trust=[]

In [3]:
import csv

with open('Dataset/Emotion_Lexicon.csv') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    Words=[]
    Anger = []
    Anticipation=[]
    Disgust=[]
    Fear=[]
    Joy=[]
    Negative=[]
    Positive=[]
    Sadness=[]
    Surprise=[]
    Trust=[]
    
    
    for row in readCSV:
        Wd = row[0]
        An =row[1]
        Ant=row[2]
        Di=row[3]
        Fe=row[4]
        Jo=row[5]
        Ne=row[6]
        Po=row[7]
        Sa=row[8]
        Su=row[9]
        tr=row[10]
        
        
        
        Words.append(Wd)
        Anger.append(An)
        Anticipation.append(Ant)
        Disgust.append(Di)
        Fear.append(Fe)
        Joy.append(Jo)
        Negative.append(Ne)
        Positive.append(Po)
        Sadness.append(Sa)
        Surprise.append(Su)
        Trust.append(tr)

In [4]:

i=0

for item in Anger:
    if item == '1':
        anger.append(lemmatizer.lemmatize(porter.stem(Words[i])))
        
    i=i+1

In [5]:


i=0

for item in Anticipation:
    if item == '1':
        anticipation.append(lemmatizer.lemmatize(porter.stem(Words[i]))) 
    i=i+1

In [6]:

i=0

for item in Disgust:
    if item == '1':
        disgust.append(lemmatizer.lemmatize(porter.stem(Words[i]))) 
    i=i+1

In [7]:
i=0

for item in Fear:
    if item == '1':
        fear.append(lemmatizer.lemmatize(porter.stem(Words[i])))
    i=i+1

In [8]:
i=0

for item in Joy:
    if item == '1':
        joy.append(lemmatizer.lemmatize(porter.stem(Words[i]))) 
    i=i+1

In [9]:
i=0

for item in Negative:
    if item == '1':
        negative.append(lemmatizer.lemmatize(porter.stem(Words[i])))
    i=i+1

In [10]:
i=0

for item in Positive:
    if item == '1':
        positive.append(lemmatizer.lemmatize(porter.stem(Words[i]))) 
    i=i+1

In [11]:
i=0

for item in Sadness:
    if item == '1':
        sadness.append(lemmatizer.lemmatize(porter.stem(Words[i]))) 
    i=i+1

In [12]:
i=0

for item in Surprise:
    if item == '1':
        surprise.append(lemmatizer.lemmatize(porter.stem(Words[i]))) 
    i=i+1

In [13]:
i=0

for item in Trust:
    if item == '1':
        trust.append(lemmatizer.lemmatize(porter.stem(Words[i]))) 
    i=i+1

In [14]:
dict={'anger' :anger,'anticipation':anticipation,'disgust':disgust,'fearCounter':fear,'joy':joy, 'negative':negative,'positive':positive, 'sadness':sadness,'surprise':surprise,'trust':trust}



import json
path='Dictionaries/Emotions.json'
with open(path, 'w') as f:
    json.dump(dict, f)

In [15]:
datafr = pd.read_csv('Dataset/Tweets.csv', encoding='latin-1')
datafr

,Unnamed: 0,Tweets,Writer
0,0,iâm proud to endorse this diverse and hopefu...,BarackObama
1,1,welcome home astrobehnken and astrodoug we lau...,BarackObama
2,2,this pandemic is far from overââand our me...,BarackObama
3,3,john believed that in all of us there exists t...,BarackObama
4,4,john spent his entire life fighting for justic...,BarackObama
...,...,...,...
12104,2015,for a minute there i was all happy thinking it...,Random
12105,2016,for the first time ever my iphone crashed itun...,Random
12106,2017,for trish sa right side ng reply ko may star a...,Random
12107,2018,forgot about them science exams tbh n,Random
12108,2019,found her jrm icons,Random

In [16]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize

def DatasetModel(tweet):
    
    phrase=[]
    text_tokens = word_tokenize(tweet)
    tokens_without_sw = [word for word in text_tokens if not word in stopwords.words()]
    for item in tokens_without_sw:
        phrase.append(lemmatizer.lemmatize(porter.stem(item)))

    
    
    
    angerCounter=0
    anticipationCounter=0
    disgustCounter=0
    fearCounter=0
    joyCounter=0
    negativeCounter=0
    positiveCounter=0
    sadnessCounter=0
    surpriseCounter=0
    trustCounter=0
    arr=[]
    for i in range(11):
        if i==0: 
            arr=anger
        elif i==1:
            arr=anticipation
        elif i==2:
            
            arr=disgust
        elif i==3:
            
            arr=fear
        elif i==4:
            
            arr=joy
        elif i==5:
            
            arr=negative
        elif i==6:
            
            arr=positive
        elif i==7:
            
            arr=sadness
        elif i==8:
            
            arr=surprise
        elif i==9:
            
            arr=trust
     
        for item in phrase:
            for wd in arr:
                if item==wd:
                    if i==0:
                        angerCounter+=1
                    elif i==1:
                        anticipationCounter+=1
                    elif i==2:
                        disgustCounter+=1
                    elif i==3:
                        fearCounter+=1
                    elif i==4:
                        joyCounter+=1
                    elif i==5:
                        negativeCounter+=1
                    elif i==6:
                        positiveCounter+=1
                    elif i==7:
                        sadnessCounter+=1
                    elif i==8:
                        surpriseCounter+=1
                    elif i==9:
                        trustCounter+=1
                    





    highest=max(angerCounter,anticipationCounter,disgustCounter,fearCounter,joyCounter,negativeCounter,positiveCounter,sadnessCounter,surpriseCounter,trustCounter)

    if highest==angerCounter and highest!=0:
        return "Anger"
    elif highest==anticipationCounter and highest!=0:
        return "Anticipation"
    elif highest==disgustCounter and highest!=0:
        return "Disgust"
    elif highest==fearCounter and highest!=0:
        return "Fear"
    elif highest==joyCounter and highest!=0:
        return "Joy"
    elif highest==negativeCounter and highest!=0:
        return "Neagtive"
    elif highest==positiveCounter and highest!=0:
        return "Positive"
    elif highest==sadnessCounter and highest!=0:
        return "Sadness"
    elif highest==surpriseCounter and highest!=0:
        return "Surprise"
    elif highest==trustCounter and highest!=0:
        return "Trust"
    else:
        return "Neutral"

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Alee\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [17]:
datafr['Emotion'] = datafr['Tweets'].apply(DatasetModel)

In [18]:
df=datafr
df

,Unnamed: 0,Tweets,Writer,Emotion
0,0,iâm proud to endorse this diverse and hopefu...,BarackObama,Positive
1,1,welcome home astrobehnken and astrodoug we lau...,BarackObama,Positive
2,2,this pandemic is far from overââand our me...,BarackObama,Trust
3,3,john believed that in all of us there exists t...,BarackObama,Positive
4,4,john spent his entire life fighting for justic...,BarackObama,Neagtive
...,...,...,...,...
12104,2015,for a minute there i was all happy thinking it...,Random,Anticipation
12105,2016,for the first time ever my iphone crashed itun...,Random,Neagtive
12106,2017,for trish sa right side ng reply ko may star a...,Random,Positive
12107,2018,forgot about them science exams tbh n,Random,Neutral
12108,2019,found her jrm icons,Random,Joy

In [19]:
frame = df[['Tweets', 'Emotion','Writer']]

In [20]:
frame

,Tweets,Emotion,Writer
0,iâm proud to endorse this diverse and hopefu...,Positive,BarackObama
1,welcome home astrobehnken and astrodoug we lau...,Positive,BarackObama
2,this pandemic is far from overââand our me...,Trust,BarackObama
3,john believed that in all of us there exists t...,Positive,BarackObama
4,john spent his entire life fighting for justic...,Neagtive,BarackObama
...,...,...,...
12104,for a minute there i was all happy thinking it...,Anticipation,Random
12105,for the first time ever my iphone crashed itun...,Neagtive,Random
12106,for trish sa right side ng reply ko may star a...,Positive,Random
12107,forgot about them science exams tbh n,Neutral,Random
12108,found her jrm icons,Joy,Random

In [21]:
df=frame
df

,Tweets,Emotion,Writer
0,iâm proud to endorse this diverse and hopefu...,Positive,BarackObama
1,welcome home astrobehnken and astrodoug we lau...,Positive,BarackObama
2,this pandemic is far from overââand our me...,Trust,BarackObama
3,john believed that in all of us there exists t...,Positive,BarackObama
4,john spent his entire life fighting for justic...,Neagtive,BarackObama
...,...,...,...
12104,for a minute there i was all happy thinking it...,Anticipation,Random
12105,for the first time ever my iphone crashed itun...,Neagtive,Random
12106,for trish sa right side ng reply ko may star a...,Positive,Random
12107,forgot about them science exams tbh n,Neutral,Random
12108,found her jrm icons,Joy,Random

In [22]:
df.to_csv('Dataset/Tweets.csv')

In [23]:
df.to_pickle('Dataset/Tweets.pkl')

In [24]:
import pandas as pd

In [25]:
df1 = pd.read_csv('Dataset\Tweets.csv', encoding='latin-1')
df1=df1.astype(str)

In [26]:
df = pd.concat([df1, df1])

In [27]:
df.to_csv('Dataset/TweetsDataset.csv')

In [28]:
df.to_pickle('Dataset/TweetsDataset.pkl')

In [29]:
df

,Unnamed: 0,Tweets,Emotion,Writer
0,0,iÃ¢ÂÂm proud to endorse this diverse and hop...,Positive,BarackObama
1,1,welcome home astrobehnken and astrodoug we lau...,Positive,BarackObama
2,2,this pandemic is far from overÃ¢ÂÂÃ¢ÂÂand ...,Trust,BarackObama
3,3,john believed that in all of us there exists t...,Positive,BarackObama
4,4,john spent his entire life fighting for justic...,Neagtive,BarackObama
...,...,...,...,...
12104,12104,for a minute there i was all happy thinking it...,Anticipation,Random
12105,12105,for the first time ever my iphone crashed itun...,Neagtive,Random
12106,12106,for trish sa right side ng reply ko may star a...,Positive,Random
12107,12107,forgot about them science exams tbh n,Neutral,Random
12108,12108,found her jrm icons,Joy,Random